CREATE DATABASE IF NOT EXISTS Book;
USE Book;


CREATE TABLE IF NOT EXISTS `Book_list` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(150) NOT NULL,
  `status` VARCHAR(45) NULL,
  `Bookcol` VARCHAR(45) NULL DEFAULT 'لم ينتهي',
  `add_in_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_in_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `Favorite` (
  `Book_ID` INT NOT NULL,
  `add_in_date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_Favorite_Book_idx` (`Book_ID` ASC),
  PRIMARY KEY (`Book_ID`),
  CONSTRAINT `fk_Favorite_Book`
    FOREIGN KEY (`Book_ID`)
    REFERENCES `Book_list` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;
